name: Verify i18n

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - release-*.*.*

jobs:
  verify-i18n:
    # Run on `grafana/grafana` only to prevent running on stolostron mirrors/forks
    if: github.repository == 'grafana/grafana'
    uses: grafana/grafana-github-actions/.github/workflows/verify-i18n.yml@main
